### ISSUE TITLE
uLottery doesn't check whether players are dead

### ISSUE THREAD

**Issue by jeoboogie** [Ullarah/MinecraftPlugins#4]
It'd be nice if uLottery filtered out dead players when selecting the winner. AFK dead players can and do win the lottery.

**Comment by Ullarah** [comment]
Good idea. I should make an exception for those who are currently suspended from the lottery.

I might add an exception list, that way staff or certain players can be excluded.

This should be done in the next day or two. Thanks for your suggestion! :)
